version: '3.8'

services:
  db:
    image: mongo
    container_name: demo-gql-data
    env_file:
      .env
    environment:
      MONGO_INITDB_DATABASE: ${DB_NAME}
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - '27019:27017'